const shapeConstants = {
  SQUARE: "SQUARE",
  CORNER_UPPER_RIGHT: "CORNER_UPPER_RIGHT",
  CORNER_LOWER_RIGHT: "CORNER_LOWER_RIGHT",
  CORNER_UPPER_LEFT: "CORNER_UPPER_LEFT",
  CORNER_LOWER_LEFT: "CORNER_LOWER_LEFT"
};

export default shapeConstants;
